version: "3.8"

services:
  postgres-metastore:
    image: postgres:13
    container_name: postgres-metastore
    restart: unless-stopped
    environment:
      POSTGRES_USER: ndh
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: metastore
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ndh -d metastore"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - system_network

  hive-metastore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hive-metastore
    restart: on-failure
    environment:
      - DB_DRIVER=postgres
      - SERVICE_NAME=metastore
      - SERVICE_OPTS=-Xmx1G -Dhive.metastore.uris=thrift://0.0.0.0:9083
    ports:
      - "9083:9083"
    volumes:
      - ./hive-config/hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      postgres-metastore:
        condition: service_healthy
    networks:
      - system_network

networks:
  system_network:
    external: true
