services:
  trino:
    image: trinodb/trino:418
    container_name: trino
    hostname: trino
    ports:
      - "9090:8080"
    volumes:
      - ./config/catalog:/etc/trino/catalog
    networks:
      - system_network

networks:
  system_network:
    external: true
    